<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Shiprestriction
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block */
?>
<?php $_element = $block->getElement() ?>
<?php $_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId() ?>

<div class="rule-tree">
    <fieldset id="<?php /* @escapeNotVerified */ echo $_jsObjectName ?>" <?php /* @escapeNotVerified */ echo $_element->serialize(['class']) ?> class="fieldset-wrapper fieldset">
        <strong class="title"><span><?php /* @escapeNotVerified */ echo $_element->getLegend() ?></span></strong>
    <div class="rule-tree-wrapper">
        <?php echo $_element->getChildrenHtml() ?>
    </div>
    </fieldset>
    <?php if ($_element->getComment()) : ?>
        <div class="admin__field-note">
            <span><?= /* @noEscape */$_element->getComment() ?></span>
        </div>
    <?php endif; ?>
</div>
<br>
<script>
require([
    "Magento_Rule/rules",
    "prototype"
], function(VarienRulesForm){

window.<?php /* @escapeNotVerified */ echo $_jsObjectName ?> = new VarienRulesForm('<?php /* @escapeNotVerified */ echo $_jsObjectName ?>', '<?php /* @escapeNotVerified */ echo $block->getNewChildUrl() ?>');
<?php if ($_element->getReadonly()) : ?>
    <?php echo $_element->getHtmlId() ?>.setReadonly(true);
<?php endif; ?>

});
</script>
